{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adminio-ui.fullname" . }}-config
  labels:
    {{- include "adminio-ui.labels" . | nindent 4 }}
{{- with .Values.configmap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
