# Default values for adminio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployment:
  containerPort: 8080
  env:
  - name: ADMINIO_HOST_PORT
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: ADMINIO_HOST_PORT
  - name: MINIO_HOST_PORT
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: MINIO_HOST_PORT
  - name: MINIO_SSL
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: MINIO_SSL
  - name: MINIO_REGION
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: MINIO_REGION
  - name: ADMINIO_CORS_DOMAIN
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: ADMINIO_CORS_DOMAIN
  - name: ADMINIO_OAUTH_ENABLE
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: ADMINIO_OAUTH_ENABLE
  - name: ADMINIO_OAUTH_PROVIDER
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: ADMINIO_OAUTH_PROVIDER
  - name: ADMINIO_OAUTH_CALLBACK
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: ADMINIO_OAUTH_CALLBACK
  - name: ADMINIO_OAUTH_CUSTOM_DOMAIN
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: ADMINIO_OAUTH_CUSTOM_DOMAIN
  - name: ADMINIO_COOKIE_NAME
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: ADMINIO_COOKIE_NAME
  - name: ADMINIO_AUDIT_LOG_ENABLE
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: ADMINIO_AUDIT_LOG_ENABLE
  - name: ADMINIO_PROBES_ENABLE
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: ADMINIO_PROBES_ENABLE
  - name: ADMINIO_METRICS_ENABLE
    valueFrom:
      configMapKeyRef:
        name: adminio-api-config
        key: ADMINIO_METRICS_ENABLE
  - name: MINIO_SECRET
    valueFrom:
      secretKeyRef:
        name: adminio-api-secret
        key: MINIO_SECRET
  - name: MINIO_ACCESS
    valueFrom:
      secretKeyRef:
        name: adminio-api-secret
        key: MINIO_ACCESS
  - name: ADMINIO_COOKIE_HASH_KEY
    valueFrom:
      secretKeyRef:
        name: adminio-api-secret
        key: ADMINIO_COOKIE_HASH_KEY
  - name: ADMINIO_COOKIE_BLOCK_KEY
    valueFrom:
      secretKeyRef:
        name: adminio-api-secret
        key: ADMINIO_COOKIE_BLOCK_KEY
  - name: ADMINIO_OAUTH_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: adminio-api-secret
        key: ADMINIO_OAUTH_CLIENT_ID
  - name: ADMINIO_OAUTH_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: adminio-api-secret
        key: ADMINIO_OAUTH_CLIENT_SECRET
image:
  repository: rzrbld/adminio-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "release-1.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "adminio-api"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 1000330001
  runAsGroup: 1000330001

securityContext:
  privileged: false
  runAsNonRoot: true

service:
  # type: NodePort
  # port: 8080
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: adminio-api.example.com
      paths: ['/']
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

configmap:
  enabled: true
  data:
    ADMINIO_HOST_PORT: ":8080"
    MINIO_HOST_PORT: "minio.example.com:9000"
    MINIO_SSL: "false"
    MINIO_REGION: "us-east-1"
    ADMINIO_CORS_DOMAIN: "*"
    ADMINIO_OAUTH_ENABLE: "false"
    ADMINIO_OAUTH_PROVIDER: "github"
    ADMINIO_OAUTH_CALLBACK: ""
    ADMINIO_OAUTH_CUSTOM_DOMAIN: ""
    ADMINIO_COOKIE_NAME: "adminiosessionid"
    ADMINIO_AUDIT_LOG_ENABLE: "false"
    ADMINIO_PROBES_ENABLE: "true"
    ADMINIO_METRICS_ENABLE: "true"


secret:
  enabled: true
  MINIO_ACCESS: "test-access"
  MINIO_SECRET: "test-secret"
  ADMINIO_COOKIE_HASH_KEY: ""
  ADMINIO_COOKIE_BLOCK_KEY: ""
  ADMINIO_OAUTH_CLIENT_ID: ""
  ADMINIO_OAUTH_CLIENT_SECRET: ""

nodeSelector: {}

tolerations: []

affinity: {}
