{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adminio.fullname" . }}-secret
  labels:
    {{- include "adminio.labels" . | nindent 4 }}
data:
  MINIO_SECRET: {{ default "" .Values.secret.MINIO_SECRET | b64enc | quote }}
  MINIO_ACCESS: {{ default "" .Values.secret.MINIO_ACCESS | b64enc | quote }}
  ADMINIO_COOKIE_HASH_KEY: {{ default "" .Values.secret.ADMINIO_COOKIE_HASH_KEY | b64enc | quote }}
  ADMINIO_COOKIE_BLOCK_KEY: {{ default "" .Values.secret.ADMINIO_COOKIE_BLOCK_KEY | b64enc | quote }}
  ADMINIO_OAUTH_CLIENT_ID: {{ default "" .Values.secret.ADMINIO_OAUTH_CLIENT_ID | b64enc | quote }}
  ADMINIO_OAUTH_CLIENT_SECRET: {{ default "" .Values.secret.ADMINIO_OAUTH_CLIENT_SECRET | b64enc | quote }}
{{- end }}
