# Default values for adminio-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployment:
  containerPort: 8000
  env:
  - name: API_BASE_URL
    valueFrom:
      configMapKeyRef:
        name: adminio-ui-config
        key: API_BASE_URL
  - name: ADMINIO_PROD
    valueFrom:
      configMapKeyRef:
        name: adminio-ui-config
        key: ADMINIO_PROD
  - name: ADMINIO_MULTI_BACKEND
    valueFrom:
      configMapKeyRef:
        name: adminio-ui-config
        key: ADMINIO_MULTI_BACKEND
  - name: ADMINIO_BACKENDS
    valueFrom:
      configMapKeyRef:
        name: adminio-ui-config
        key: ADMINIO_BACKENDS
  - name: NGX_ROOT_PATH
    valueFrom:
      configMapKeyRef:
        name: adminio-ui-config
        key: NGX_ROOT_PATH
  - name: NGX_PORT
    valueFrom:
      configMapKeyRef:
        name: adminio-ui-config
        key: NGX_PORT


image:
  repository: rzrbld/adminio-ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "release-1.4"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "adminio-ui"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}


podSecurityContext:
  runAsUser: 1000330001
  runAsGroup: 1000330001

securityContext:
  privileged: false
  runAsNonRoot: true


service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: adminio-ui.example.com
      paths: ['/']
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 64Mi

configmap:
  enabled: true
  data:
    API_BASE_URL: "adminio-api:8080"
    ADMINIO_PROD: "false"
    ADMINIO_MULTI_BACKEND: "false"
    ADMINIO_BACKENDS: '[{"name":"myminio","url":"http://localhost:8080"},{"name":"localhost","url":"http://localhost:8081"},{"name":"error","url":"http://localhost:8082"}]'
    NGX_ROOT_PATH: "/"
    NGX_PORT: "8000"


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
